POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Rest teeest",
    "author": "Matti npoika123",
    "url": "url513",
    "likes": "763",
    "userId": "6634149e87f95a8f11614607"
}